Fix permission error

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -197,7 +197,7 @@ jobs:
       - name: Run Integration Test
         run: |
           cd integration
-          npx jest --ci --reporters=default --reporters=jest-junit || echo "tests failed"
+          sudo npx jest --ci --reporters=default --reporters=jest-junit || echo "tests failed"
           test_url="$(curl -X POST --data-binary @junit.xml https://test.compound.finance/test)"
           echo "::set-output name=test_url::$test_url"
         id: int_test
