Add Integration Tests for Golden Paths (#75)
* Add Integration Tests for Golden Paths

This patch adds integration tests to test the golden path scenario for Compound Chain. The goal is to actually deploy a Cash Token, Starport and run Compound Chain against some local node and test real-life behaviors from JavaScript. The goal is to make sure that all components correctly talk to one another. These tests will obviously be slower to run than unit tests, so we may restrict how and when we run these in CI.

* Remove fancy .? syntax

* Add back cargo compilation step

* s/unit/integration/g

* Update README

* Move util functions to own file

* Upgrade test more

* Allow everything for now

* more fixes

* Upgrade to newer version of Substrate

* Fix golden path test for Magic Extract

* add back per extrinsic checking

* Move back to compound-chain#master

* cargo fmt

* Bump down dep as per issue from recent minor package update

* Upgrade mocks for new Substrate version

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -64,33 +64,120 @@ jobs:
           files: unit-test-results.xml
         continue-on-error: true
 
+  integration-tests:
+    name: integration-tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Test Note for ${{ github.ref }}
+        run: |
+          echo Integration testing ${GITHUB_REF}...
+
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Use Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: '12.x'
+
+      - uses: actions/cache@v2
+        with:
+          path: '**/node_modules'
+          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
+
+      # TODO: cache this step somehow if necessary?
+      #  could use parity/substrate image maybe but requires entrypoint on every step
+      - name: Substrate setup
+        run: |
+          ./scripts/get_substrate.sh --fast
+
+      - name: Rust Cache
+        uses: Swatinem/rust-cache@v1.0.1
+    
+      - name: Install yarn ethereum dependencies
+        run: cd ethereum && yarn install
+      
+      - name: Install integration test ethereum dependencies
+        run: cd integration && yarn install
+
+      - name: Install solc
+        run: |
+          sudo wget https://github.com/ethereum/solidity/releases/download/v0.7.5/solc-static-linux -O /usr/local/bin/solc
+          sudo chmod +x /usr/local/bin/solc
+
+      - name: Compile Ethereum contracts
+        run: |
+          cd ethereum
+          yarn compile
+
+      - name: Build Compound Chain
+        run: |
+          cargo +nightly build --release
+
+      - name: Run Integration Test
+        run: |
+          cd integration
+          npx jest --ci --reporters=default --reporters=jest-junit || echo "tests failed"
+          test_url="$(curl -X POST --data-binary @junit.xml https://test.compound.finance/test)"
+          echo "::set-output name=test_url::$test_url"
+        id: int_test
+
+      - name: Link to Integration Results
+        uses: unsplash/comment-on-pr@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          msg: "🫖 [View Integration Test Results](${{steps.int_test.outputs.test_url}})"
+          check_for_duplicate_msg: false
+        continue-on-error: true
+
+      - name: Upload Integration Test Results
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: Integration Test Results
+          path: integration/junit.xml
+        continue-on-error: true
+
+      - name: Publish Integration Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v1.6
+        if: always()
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          files: integration/junit.xml
+        continue-on-error: true
+
   eth-tests:
     name: eth-tests
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: ethereum
+
     strategy:
       matrix:
         node-version: [12.x]
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Use Node.js
-      uses: actions/setup-node@v1
-      with:
-        node-version: '12.x'
-    - uses: actions/cache@v2
-      with:
-        path: '**/node_modules'
-        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
+      - uses: actions/checkout@v2
 
-    - name: Install dependencies
-      run: yarn install
-    - name: Install solc
-      run:
-        |
+      - name: Use Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: '12.x'
+
+      - uses: actions/cache@v2
+        with:
+          path: '**/node_modules'
+          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
+
+      - name: Install dependencies
+        run: yarn install
+
+      - name: Install solc
+        run: |
           sudo wget https://github.com/ethereum/solidity/releases/download/v0.7.5/solc-static-linux -O /usr/local/bin/solc
           sudo chmod +x /usr/local/bin/solc
-    - name: Run tests
-      run: yarn test
+
+      - name: Run tests
+        run: yarn test
